agro/urls.py
from django.urls import path

from .views import HarvesterFormView, FarmFormView, IndexView

app_name = 'agro'

urlpatterns = (
    path('', IndexView.as_view(), name='index_view'),
    path('harvester/', HarvesterFormView.as_view(), name='harvester_view'),
    path('farm/', FarmFormView.as_view(), name='farm_view'),
)

agromet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('agro/', include('agro.urls', namespace='agro')),
    path('admin/', admin.site.urls),
]

agro/models.py
from django.db import models


class Harvester(models.Model):

    load_num = models.IntegerField()
    harvester = models.CharField(max_length=255)
    date = models.DateField()
    time = models.TimeField()
    field = models.CharField(max_length=255)
    harvest_type = models.CharField(max_length=255)
    variety = models.CharField(max_length=255)
    truck = models.IntegerField()
    acres_harvested = models.DecimalField(max_digits=6, decimal_places=2)
    passes = models.DecimalField(max_digits=6, decimal_places=2)
    comments = models.TextField()
    cwt = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.harvester


class Farm(models.Model):

    load_num = models.ForeignKey('Harvester', on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    tub_no = models.IntegerField()
    bin_no = models.IntegerField()
    b_trks = models.DecimalField(max_digits=6, decimal_places=2)
    pulp_temp = models.DecimalField(max_digits=6, decimal_places=2)
    comments = models.TextField()

    def __str__(self):
        return "{}, Tub# {}, Bin# {}".format(self.load_num, self.tub_no, self.bin_no)

agro/forms.py
from django import forms

from .models import Harvester, Farm


class HarvesterForm(forms.ModelForm):

    class Meta:
        model = Harvester
        fields = ['load_num', 'harvester', 'date', 'time', 'field', 'harvest_type', 'variety', 'truck',
                  'acres_harvested', 'passes', 'comments', 'cwt']


class FarmForm(forms.ModelForm):

    class Meta:
        model = Farm
        fields = ['load_num', 'date', 'time', 'tub_no', 'bin_no', 'b_trks', 'pulp_temp', 'comments']

agro/views.py
from django import forms
from django.shortcuts import reverse, render
from django.http import HttpResponseRedirect
from django.views import View, generic

from .forms import HarvesterForm, FarmForm
from .models import Harvester, Farm


class IndexView(generic.ListView):
    model = Harvester
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['harvesters'] = Harvester.objects.all()
        return context


class HarvesterFormView(View):
    form_class = HarvesterForm
    template_name = 'agro/harvester.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            harvester = form.save()
            request.session['harvester_id'] = harvester.id
            return HttpResponseRedirect(reverse('agro:farm_view'))
        return render(request, self.template_name, {'form': form, 'errors': form.errors})


class FarmFormView(View):
    form_class = FarmForm
    template_name = 'agro/farm.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)
        context = dict()
        if 'harvester_id' in request.session:
            context['harvester_id'] = request.session.pop('harvester_id')
            form.fields['load_num'].required = False
            form.fields['load_num'].widget = forms.HiddenInput()
        context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            farm = form.save()
            return HttpResponseRedirect(reverse('agro:index_view'))
        return render(request, self.template_name, {'form': form, 'errors': form.errors})

agro/templates/agro/farm.html
{% if errors %}
    {{ errors }}
{% endif %}
<form action="/agro/farm/" method="post">
    {% csrf_token %}
    <table>
        <tr><th><label for="id_load_num">Load num:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><select name="load_num" required id="id_load_num">
          <option value="" selected>---------</option>
          {% for each in form.fields.load_num.choices.queryset %}
            <option value="{{each.id}}" {% if each.id == harvester_id %} selected='selected' {% endif %} >{{each}}</option>
          {% endfor %}
        </select></td></tr>
        <tr><th><label for="id_date">Date:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="date" required id="id_date" /></td></tr>
        <tr><th><label for="id_time">Time:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="time" required id="id_time" /></td></tr>
        <tr><th><label for="id_tub_no">Tub no:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="tub_no" required id="id_tub_no" /></td></tr>
        <tr><th><label for="id_bin_no">Bin no:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="bin_no" required id="id_bin_no" /></td></tr>
        <tr><th><label for="id_b_trks">B trks:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="b_trks" step="0.01" required id="id_b_trks" /></td></tr>
        <tr><th><label for="id_pulp_temp">Pulp temp:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="pulp_temp" step="0.01" required id="id_pulp_temp" /></td></tr>
        <tr><th><label for="id_comments">Comments:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><textarea name="comments" cols="40" rows="10" required id="id_comments">
        </textarea></td></tr>
    </table>
    <input type="submit" value="Submit">

</form>

agro/templates/agro/harvester.html
{% if errors %}
    {{ errors }}
{% endif %}
<form action="/agro/harvester/" method="post">
    {% csrf_token %}
    <table>
        <tr><th><label for="id_load_num">Load num:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="load_num" required id="id_load_num" /></td></tr>
        <tr><th><label for="id_harvester">Harvester:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="harvester" maxlength="255" required id="id_harvester" /></td></tr>
        <tr><th><label for="id_date">Date:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="date" required id="id_date" /></td></tr>
        <tr><th><label for="id_time">Time:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="time" required id="id_time" /></td></tr>
        <tr><th><label for="id_field">Field:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="field" maxlength="255" required id="id_field" /></td></tr>
        <tr><th><label for="id_harvest_type">Harvest type:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="harvest_type" maxlength="255" required id="id_harvest_type" /></td></tr>
        <tr><th><label for="id_variety">Variety:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="text" name="variety" maxlength="255" required id="id_variety" /></td></tr>
        <tr><th><label for="id_truck">Truck:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="truck" required id="id_truck" /></td></tr>
        <tr><th><label for="id_acres_harvested">Acres harvested:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="acres_harvested" step="0.01" required id="id_acres_harvested" /></td></tr>
        <tr><th><label for="id_passes">Passes:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="passes" step="0.01" required id="id_passes" /></td></tr>
        <tr><th><label for="id_comments">Comments:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><textarea name="comments" cols="40" rows="10" required id="id_comments">
        </textarea></td></tr>
        <tr><th><label for="id_cwt">Cwt:</label></th><td><ul class="errorlist"><li>This field is required.</li></ul><input type="number" name="cwt" step="0.01" required id="id_cwt" /></td></tr>
    </table>
    <input type="submit" value="Submit">
</form>

agro/templates/agro/harvester_detail.html
{% if errors %}
    {{ errors }}
{% endif %}
{{ form.as_p }}

<a href="{% url 'agro:harvester_edit' pk=pk%}">Edit...</a>

agro/templates/agro/harvester_edit.html
{% if errors %}
    {{ errors }}
{% endif %}
<form action="/agro/harvester/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

agro/templates/agro/harvester_list.html
<ul>
    {% for harvester in harvesters %}
        <li>
            {{harvester.harvester}}  ==>  {% for farm in harvester.farm_set.all %} <{{ farm }}> {% empty %} None {% endfor %}
        </li>
    {% endfor %}
    <a href="{% url 'agro:harvester_view' %}">Add Harvester</a>
</ul>